soc: smcinvoke: Rename size_add to size_add_soc
Inlined with changes implement size_t saturating arithmetic helpers.

Log:
../drivers/soc/qcom/smcinvoke.c:591:22: error: redefinition of 'size_add'
  591 | static inline size_t size_add(size_t a, size_t b)
      |                      ^~~~~~~~
In file included from ../include/linux/device.h:28,
                 from ../drivers/soc/qcom/smcinvoke.c:11:
../include/linux/overflow.h:273:35: note: previous definition of 'size_add' with type 'size_t(size_t,  size_t)' {aka 'long unsigned int(long unsigned int,  long unsigned int)'}
  273 | static inline size_t __must_check size_add(size_t addend1, size_t addend2)
      |                                   ^~~~~~~~

[TogoFire]: Add log.

Fixes: 1ab137a90eea ("overflow: Implement size_t saturating arithmetic helpers")
Signed-off-by: Rudi Setiyawan <diphons@gmail.com>
Change-Id: I5d2d8f3f1e06a4c18106614d936ea13d0b6f9735
Signed-off-by: TogoFire <togofire@mailfence.com>